coverage:
  precision: 1
  round: down
  range: "50...90"

  status:
    project:
      default:
       threshold: 0.05
    patch:
      default:
       threshold: 0.05
    changes:
      default: off

comment:
  layout: "header"
  behavior: new
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**.pb.go$"
  - "examples/**$"
